# Change these first
owner: z0ph # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: zoph.me
    url: https://zoph.me
    icon: https://zoph.me/favicon-32x32.png
  - name: zoph.io
    url: https://zoph.io
    icon: https://zoph.io/img/favicon-32x32.png
  - name: AWS Security Digest
    url: https://awssecuritydigest.com
    icon: https://assets.super.so/36807d35-bcb2-4696-929d-8ce7dcd9d904/uploads/favicon/7baf297c-b988-4b52-ab1d-a76e98ba2e31.png
  - name: unusd.cloud
    url: https://unusd.cloud
    icon: https://unusd.cloud/images/favicon.png
  - name: unusd.cloud - backstage
    url: https://app.unusd.cloud
    icon: https://unusd.cloud/images/favicon.png
  - name: Home Automation
    url: $SECRET_SITE
    icon: https://www.jeedom.com/favicon.ico


assignees:
  - z0ph

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.zoph.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://zoph.io/img/logo-small.png
  name: Upptime - zoph.me
  introTitle: "Monitoring for zoph.me endpoints"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: zoph.me
      href: https://zoph.me
    - title: zoph.io
      href: https://zoph.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
