# Change these first
owner: z0ph # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: zoph.me
    url: https://zoph.me
  - name: zoph.io
    url: https://zoph.io
  - name: Home Automation
    url: $HOME_AUTOMATION
    expectedStatusCodes:
      - 302

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.zoph.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.zoph.me
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Personal Monitoring for zoph.me endpoints.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
